<?php

namespace Shared\Audit;

/**
 * PRD Lampiran A / DATABASE_SCHEMA §7 — backed-enum aplikasi, no DB CHECK.
 */
enum ActionType: string
{
    // Auth
    case LOGIN_SUCCESS = 'LOGIN_SUCCESS';
    case LOGIN_FAILED = 'LOGIN_FAILED';
    case LOGIN_LOCKED_OUT = 'LOGIN_LOCKED_OUT';
    case LOGOUT = 'LOGOUT';
    case TWOFA_SETUP = 'TWOFA_SETUP';
    case TWOFA_VERIFIED = 'TWOFA_VERIFIED';
    case TWOFA_FAILED = 'TWOFA_FAILED';
    case TWOFA_RECOVERY_USED = 'TWOFA_RECOVERY_USED';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';
    case STEPUP_REAUTH = 'STEPUP_REAUTH';
    case STEPUP_FAILED = 'STEPUP_FAILED';

    // User / Role
    case USER_CREATED = 'USER_CREATED';
    case USER_UPDATED = 'USER_UPDATED';
    case USER_DEACTIVATED = 'USER_DEACTIVATED';
    case USER_REACTIVATED = 'USER_REACTIVATED';
    case ROLE_ASSIGNED = 'ROLE_ASSIGNED';
    case ROLE_CHANGED = 'ROLE_CHANGED';
    case PASSWORD_RESET_BY_ADMIN = 'PASSWORD_RESET_BY_ADMIN';

    // Lookup
    case LOOKUP_CREATED = 'LOOKUP_CREATED';
    case LOOKUP_UPDATED = 'LOOKUP_UPDATED';
    case LOOKUP_DEACTIVATED = 'LOOKUP_DEACTIVATED';
    case LOOKUP_REACTIVATED = 'LOOKUP_REACTIVATED';
    case LOOKUP_REQUEST_SUBMITTED = 'LOOKUP_REQUEST_SUBMITTED';
    case LOOKUP_REQUEST_APPROVED = 'LOOKUP_REQUEST_APPROVED';
    case LOOKUP_REQUEST_REJECTED = 'LOOKUP_REQUEST_REJECTED';

    // Company
    case COMPANY_CREATED = 'COMPANY_CREATED';
    case COMPANY_UPDATED = 'COMPANY_UPDATED';
    case COMPANY_REQUESTED = 'COMPANY_REQUESTED';
    case COMPANY_APPROVED = 'COMPANY_APPROVED';
    case COMPANY_REJECTED = 'COMPANY_REJECTED';
    case COMPANY_DEACTIVATED = 'COMPANY_DEACTIVATED';
    case COMPANY_REACTIVATED = 'COMPANY_REACTIVATED';

    // Candidate
    case CANDIDATE_CREATED = 'CANDIDATE_CREATED';
    case CANDIDATE_SUBMITTED = 'CANDIDATE_SUBMITTED';
    case CANDIDATE_APPROVED = 'CANDIDATE_APPROVED';
    case CANDIDATE_REJECTED = 'CANDIDATE_REJECTED';
    case CANDIDATE_REVISION_SUBMITTED = 'CANDIDATE_REVISION_SUBMITTED';
    case CANDIDATE_UPDATED = 'CANDIDATE_UPDATED';
    case CANDIDATE_SOFT_DELETED = 'CANDIDATE_SOFT_DELETED';
    case CANDIDATE_RESTORED = 'CANDIDATE_RESTORED';
    case IDENTITY_DOC_VIEWED = 'IDENTITY_DOC_VIEWED';
    case CANDIDATE_PHOTO_UPLOADED = 'CANDIDATE_PHOTO_UPLOADED';
    case SIMILARITY_MATCH_SHOWN = 'SIMILARITY_MATCH_SHOWN';
    case CANDIDATE_ANONYMIZED = 'CANDIDATE_ANONYMIZED';

    // Interview (Jobs)
    case IC_CREATED = 'IC_CREATED';
    case IC_SUBMITTED = 'IC_SUBMITTED';
    case IC_APPROVED = 'IC_APPROVED';
    case IC_REJECTED = 'IC_REJECTED';
    case IC_CANCELLED = 'IC_CANCELLED';
    case IC_CLOSE_REQUESTED = 'IC_CLOSE_REQUESTED';
    case IC_CLOSED = 'IC_CLOSED';
    case CANDIDATE_PULLED = 'CANDIDATE_PULLED';
    case PARTICIPATION_STATUS_CHANGED = 'PARTICIPATION_STATUS_CHANGED';
    case EXPEL_REQUESTED = 'EXPEL_REQUESTED';
    case EXPEL_APPROVED = 'EXPEL_APPROVED';
    case EXPEL_REJECTED = 'EXPEL_REJECTED';

    // Guest
    case GUEST_LINK_REQUESTED = 'GUEST_LINK_REQUESTED';
    case GUEST_LINK_APPROVED = 'GUEST_LINK_APPROVED';
    case GUEST_LINK_REJECTED = 'GUEST_LINK_REJECTED';
    case GUEST_ACCESS = 'GUEST_ACCESS';
    case GUEST_DETAIL_VIEWED = 'GUEST_DETAIL_VIEWED';

    // Placement
    case PC_CREATED = 'PC_CREATED';
    case PC_SUBMITTED = 'PC_SUBMITTED';
    case PC_APPROVED = 'PC_APPROVED';
    case PC_REJECTED = 'PC_REJECTED';
    case PC_CANCELLED = 'PC_CANCELLED';
    case BATCH_SENT = 'BATCH_SENT';
    case FORCE_MAJEUR_ADDED = 'FORCE_MAJEUR_ADDED';
    case FM_REJECTED = 'FM_REJECTED';
    case PLACEMENT_STATUS_CHANGED = 'PLACEMENT_STATUS_CHANGED';
    case RESIGN_REQUESTED = 'RESIGN_REQUESTED';
    case RESIGN_APPROVED = 'RESIGN_APPROVED';
    case RESIGN_REJECTED = 'RESIGN_REJECTED';
    case PLACEMENT_EXPEL_REQUESTED = 'PLACEMENT_EXPEL_REQUESTED';
    case PLACEMENT_EXPEL_APPROVED = 'PLACEMENT_EXPEL_APPROVED';
    case PLACEMENT_EXPEL_REJECTED = 'PLACEMENT_EXPEL_REJECTED';
    case CONTAINER_ARCHIVED = 'CONTAINER_ARCHIVED';
}
